spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/phoneshop_night
  username: phoneshop_night
  password: Sakda119
 jpa:
  properties: 
   hibernate:
   dialect: or.hibernate.dialect.PostgreSQLDialect
  hibernate:
   ddl-auto: update
 mvc:
  pathmatch:
   matching-strategy: ant_path_matcher
 liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yml